version: "3"

services:

  postgresql:
    image: postgres:15
    ports:
      - "5433:5433"
    environment:
      - PGPORT=5433
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo
